# Project Information
site_name: J-Physics Wiki
site_description: 初中物理wiki

# 导航
nav:
  - 介绍:
    - 开始阅读: index.md
    - 方针: intro/policy.md
    - 参与编写: intro/how.md
  - 运动学:
    - 运动学介绍: kinematics/intro.md
  - 声学:
    - 声学介绍: acoustics/intro.md
  - 光学:
    - 光学介绍: optics/intro.md
  - 力学:
    - 力学介绍: mechanics/intro.md
  - 热学:
    - 热学介绍: calorifics/intro.md
  - 电学: 
    - 电学介绍: electricity/intro.md
  - 磁学:
    - 磁学介绍: magnetism/intro.md

# Theme
theme:
  name: material
  language: 'zh'
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  include_search_page: false
  search_index_only: true
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.tabs.sticky
  font:
    text: 'Noto Sans CJK SC'
    code: 'Fira Mono'
