name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - run: pip install mkdocs-ezlinks-plugin
      - run: pip3 install mkdocs-git-authors-plugin
      - run: mkdocs gh-deploy --force
# 我也不知道为什么失败了，调试1
# 又TM失败了，调试2，这东西坑太TM大了，github的安全政策改了，原始文档也改了，但中文翻译没有
# 前车之鉴：不可以开启gh-pages分支的强制推送保护
